### ISSUE TITLE
Explore "Tiled" and how can we use it to design our game world

### ISSUE THREAD

**Issue by KShivendu** [OpenLake/Virtual-IIT-Bhilai#3]
Explore [Tiled](https://thorbjorn.itch.io/tiled) and figure out how can we use it to design our game world. Also, find out websites that can be used to find sprites and other assets for our game. All of this should be submitted as a pdf report.

**Comment by KridaCreations** [comment]
Okay bhaiya, will do it

**Comment by KShivendu** [comment]
We've moved to Godot. So it's not useful now.
